# Generated by Django 4.2.16 on 2024-10-19 20:07

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_note_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='body',
            field=tinymce.models.HTMLField(null=True),
        ),
    ]
